version: '3.8'

services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: db_observatorio
      POSTGRES_USER: software_observatorio
      POSTGRES_PASSWORD: software_observatorio
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db-init/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  backend:
    build:
      context: ./observatorio_api
      dockerfile: Dockerfile
    restart: always
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: db_observatorio
      DB_USER: software_observatorio
      DB_PASSWORD: software_observatorio
      COSMOS_ENDPOINT: https://datos-cosmos.documents.azure.com:443/ 
      COSMOS_KEY: qiQcJSvCarkoxOemEpqvzZeA3xk2AoJIaHOSzuR0IcfsZxvAllc4BDoPsid5p1EpSeeFupt9JAPTACDbUyxgAw==
      COSMOS_DB: PUEAR
      TTN_SERVER: mqtt://nam1.cloud.thethings.network:1883
      TTN_USERNAME: puar-unl-esp32@ttn
      TTN_PASSWORD: NNSXS.FGSQU3PH2K2E32I5U5QDUFKURE4OB42PWDP6N7A.GBTQGXU4TRE3ELIOBWTBLGXDOFQPFIN5UH6CVDHU27Q2E4XMHO3Q
      TTN_EMA: v3/puar-unl-esp32@ttn/devices/eui-70b3d57ed0060a67/up
      TTN_EHA: v3/puar-unl-esp32@ttn/devices/eui-70b3d57ed00611db/up
      KEY_SQ: OBSERVATORIO-IOT-MQTT
      KEY: OBSERVATORIO-IOT
    depends_on:
      - db
    ports:
      - "3006:3006"
    networks:
      - app-network

  frontend:
    build:
      context: ./observatorio_web
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - backend
    ports:
      - "8080:80"
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
