version: '3.8'

services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: observatorio
      POSTGRES_USER: observatorio
      POSTGRES_PASSWORD: secret_password_here
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend

  backend:
    build:
      context: ./observatorio_api
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./observatorio_api/.env
    environment:

    depends_on:
      - db
    ports:
      - "3006:3006"
    networks:
      - backend

  frontend:
    build:
      context: ./observatorio_web
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    networks:
      - backend
      - frontend_net

volumes:
  db-data:

networks:
  backend:
  frontend_net:
